CREATE TABLE IF NOT EXISTS ops_projects (
  id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id           INT UNSIGNED NOT NULL DEFAULT 1,
  client_id           INT UNSIGNED NOT NULL,
  name                VARCHAR(200) NOT NULL,
  stage               VARCHAR(80)  NOT NULL DEFAULT 'Lead',
  owner               VARCHAR(100) NOT NULL DEFAULT '',
  start_date          DATE DEFAULT NULL,
  deadline            DATE DEFAULT NULL,
  health              ENUM('green','yellow','red') NOT NULL DEFAULT 'green',
  priority            ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  quoted              DECIMAL(12,2) NOT NULL DEFAULT 0,
  received            DECIMAL(12,2) NOT NULL DEFAULT 0,
  balance             DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_status      ENUM('pending','partial','paid','overdue') NOT NULL DEFAULT 'pending',
  next_collection_trigger VARCHAR(200) DEFAULT NULL,
  collection_target_date  DATE DEFAULT NULL,
  current_work        TEXT,
  next_action         TEXT,
  next_deadline       DATE DEFAULT NULL,
  founder_note        TEXT,
  blocker             TEXT,
  created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_tenant (tenant_id),
  INDEX idx_client (client_id),
  INDEX idx_stage (stage),
  INDEX idx_health (health)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
