CREATE TABLE IF NOT EXISTS `scan_invoice_line_items` (
  `line_item_id`     INT(11) NOT NULL AUTO_INCREMENT,
  `invoice_id`       INT(11) NOT NULL,
  `product_id`       INT(11) DEFAULT NULL,
  `sku`              VARCHAR(100) DEFAULT NULL,
  `product_name`     VARCHAR(255) NOT NULL,
  `hsn_code`         VARCHAR(20) DEFAULT NULL,
  `quantity`         DECIMAL(10,3) NOT NULL,
  `unit_price`       DECIMAL(12,2) NOT NULL,
  `discount`         DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `taxable_value`    DECIMAL(12,2) NOT NULL,
  `cgst_rate`        DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `cgst_amount`      DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `sgst_rate`        DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `sgst_amount`      DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `igst_rate`        DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `igst_amount`      DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `total_amount`     DECIMAL(12,2) NOT NULL,
  `confidence_score` DECIMAL(5,2) DEFAULT NULL,
  `created_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`line_item_id`),
  KEY `idx_scan_li_invoice`  (`invoice_id`),
  KEY `idx_scan_li_product`  (`product_id`),
  CONSTRAINT `fk_scan_li_invoice` FOREIGN KEY (`invoice_id`) REFERENCES `scan_invoices` (`invoice_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_scan_li_product` FOREIGN KEY (`product_id`) REFERENCES `invoice_products` (`product_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
