CREATE TABLE IF NOT EXISTS `gst_records` (
  `gst_record_id`    INT(11) NOT NULL AUTO_INCREMENT,
  `tenant_id`        INT NOT NULL,
  `invoice_id`       INT(11) NOT NULL,
  `line_item_id`     INT(11) DEFAULT NULL,
  `gstin_supplier`   VARCHAR(15) DEFAULT NULL,
  `gstin_recipient`  VARCHAR(15) DEFAULT NULL,
  `hsn_code`         VARCHAR(20) DEFAULT NULL,
  `taxable_value`    DECIMAL(12,2) NOT NULL,
  `cgst_rate`        DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `cgst_amount`      DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `sgst_rate`        DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `sgst_amount`      DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `igst_rate`        DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `igst_amount`      DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `total_tax`        DECIMAL(12,2) NOT NULL,
  `supply_type`      ENUM('b2b','b2c') NOT NULL DEFAULT 'b2c',
  `transaction_date` DATE NOT NULL,
  `financial_year`   VARCHAR(7) NOT NULL,
  `quarter`          TINYINT NOT NULL,
  `month`            TINYINT NOT NULL,
  `created_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`gst_record_id`),
  KEY `idx_gst_tenant`       (`tenant_id`),
  KEY `idx_gst_tenant_fy`    (`tenant_id`, `financial_year`),
  KEY `idx_gst_tenant_month` (`tenant_id`, `financial_year`, `month`),
  KEY `idx_gst_invoice`      (`invoice_id`),
  CONSTRAINT `fk_gst_scan_invoice`   FOREIGN KEY (`invoice_id`) REFERENCES `scan_invoices` (`invoice_id`),
  CONSTRAINT `fk_gst_line_item`      FOREIGN KEY (`line_item_id`) REFERENCES `scan_invoice_line_items` (`line_item_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
