CREATE TABLE IF NOT EXISTS `marketplace_sales_orders` (
  `order_id`              INT(11) NOT NULL AUTO_INCREMENT,
  `tenant_id`             INT NOT NULL,
  `invoice_id`            INT(11) NOT NULL,
  `customer_id`           INT(11) DEFAULT NULL,
  `order_number`          VARCHAR(100) NOT NULL,
  `order_date`            DATE NOT NULL,
  `marketplace`           ENUM('amazon','flipkart','meesho','other') NOT NULL,
  `marketplace_order_id`  VARCHAR(200) DEFAULT NULL,
  `subtotal`              DECIMAL(12,2) NOT NULL,
  `discount`              DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `tax_amount`            DECIMAL(12,2) NOT NULL,
  `shipping_charges`      DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `commission_amount`     DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `total_amount`          DECIMAL(12,2) NOT NULL,
  `net_revenue`           DECIMAL(12,2) NOT NULL,
  `status`                ENUM('completed','pending','cancelled','returned') NOT NULL DEFAULT 'completed',
  `created_at`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`            DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  KEY `idx_mp_orders_tenant`        (`tenant_id`),
  KEY `idx_mp_orders_tenant_date`   (`tenant_id`, `order_date`),
  KEY `idx_mp_orders_tenant_market` (`tenant_id`, `marketplace`),
  KEY `idx_mp_orders_tenant_status` (`tenant_id`, `status`),
  KEY `idx_mp_orders_invoice`       (`invoice_id`),
  CONSTRAINT `fk_mp_orders_invoice`  FOREIGN KEY (`invoice_id`) REFERENCES `scan_invoices` (`invoice_id`),
  CONSTRAINT `fk_mp_orders_customer` FOREIGN KEY (`customer_id`) REFERENCES `invoice_customers` (`customer_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
