CREATE TABLE IF NOT EXISTS `scan_invoices` (
  `invoice_id`          INT(11) NOT NULL AUTO_INCREMENT,
  `tenant_id`           INT NOT NULL,
  `file_path`           VARCHAR(500) NOT NULL,
  `file_type`           ENUM('pdf','jpg','png') NOT NULL,
  `original_filename`   VARCHAR(255) NOT NULL,
  `invoice_number`      VARCHAR(100) DEFAULT NULL,
  `invoice_date`        DATE DEFAULT NULL,
  `marketplace`         ENUM('amazon','flipkart','meesho','other') NOT NULL DEFAULT 'other',
  `vendor_name`         VARCHAR(255) DEFAULT NULL,
  `vendor_gstin`        VARCHAR(15) DEFAULT NULL,
  `customer_id`         INT(11) DEFAULT NULL,
  `subtotal`            DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `tax_amount`          DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `total_amount`        DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `processing_status`   ENUM('pending','processing','review','approved','rejected','error') NOT NULL DEFAULT 'pending',
  `ai_confidence_score` DECIMAL(5,2) DEFAULT NULL,
  `extracted_data`      JSON DEFAULT NULL,
  `validated_data`      JSON DEFAULT NULL,
  `error_message`       TEXT DEFAULT NULL,
  `processed_at`        DATETIME DEFAULT NULL,
  `approved_at`         DATETIME DEFAULT NULL,
  `created_at`          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`          DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`invoice_id`),
  KEY `idx_scan_inv_tenant`        (`tenant_id`),
  KEY `idx_scan_inv_tenant_status` (`tenant_id`, `processing_status`),
  KEY `idx_scan_inv_tenant_market` (`tenant_id`, `marketplace`),
  KEY `idx_scan_inv_tenant_date`   (`tenant_id`, `invoice_date`),
  CONSTRAINT `fk_scan_inv_customer` FOREIGN KEY (`customer_id`) REFERENCES `invoice_customers` (`customer_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
