import { Component, useEffect, Suspense, lazy } from "react";
import { useSearchParams } from "react-router-dom";

const BATCH_0 = {
  "AccountingLineRow": lazy(() => import("./preview-demos/AccountingLineRowDemo")),
  "AccountingSectionCard": lazy(() => import("./preview-demos/AccountingSectionCardDemo")),
  "ActionButtons": lazy(() => import("./preview-demos/ActionButtonsDemo")),
  "ActionButtonsCard": lazy(() => import("./preview-demos/ActionButtonsCardDemo")),
  "ActionCellWithStopPropagation": lazy(() => import("./preview-demos/ActionCellWithStopPropagationDemo")),
  "ActionUploadCard": lazy(() => import("./preview-demos/ActionUploadCardDemo")),
  "ActionsSideCard": lazy(() => import("./preview-demos/ActionsSideCardDemo")),
  "ActiveBadge": lazy(() => import("./preview-demos/ActiveBadgeDemo")),
  "ActiveFilterChip": lazy(() => import("./preview-demos/ActiveFilterChipDemo")),
  "ActiveFilterCountBadge": lazy(() => import("./preview-demos/ActiveFilterCountBadgeDemo")),
  "ActiveInactiveStatusPill": lazy(() => import("./preview-demos/ActiveInactiveStatusPillDemo")),
  "ActivityFeedItem": lazy(() => import("./preview-demos/ActivityFeedItemDemo")),
  "ActivityTimelineItem": lazy(() => import("./preview-demos/ActivityTimelineItemDemo")),
  "ActivityTypeBadge": lazy(() => import("./preview-demos/ActivityTypeBadgeDemo")),
  "AddToCatalogOverlay": lazy(() => import("./preview-demos/AddToCatalogOverlayDemo")),
  "AgingBucketGrid": lazy(() => import("./preview-demos/AgingBucketGridDemo")),
  "AgingBucketTile": lazy(() => import("./preview-demos/AgingBucketTileDemo")),
  "AiAnalystPanel": lazy(() => import("./preview-demos/AiAnalystPanelDemo")),
  "AiAutofillButton": lazy(() => import("./preview-demos/AiAutofillButtonDemo")),
  "AiBusyTextSwap": lazy(() => import("./preview-demos/AiBusyTextSwapDemo")),
  "AiCheckFlagRow": lazy(() => import("./preview-demos/AiCheckFlagRowDemo")),
  "AiHealthScoreRing": lazy(() => import("./preview-demos/AiHealthScoreRingDemo")),
  "AiList": lazy(() => import("./preview-demos/AiListDemo")),
  "AmPmTimePicker": lazy(() => import("./preview-demos/AmPmTimePickerDemo")),
  "AmountInputWithFillButton": lazy(() => import("./preview-demos/AmountInputWithFillButtonDemo")),
  "AmountRangeFilter": lazy(() => import("./preview-demos/AmountRangeFilterDemo")),
  "AmountWithRateAnnotation": lazy(() => import("./preview-demos/AmountWithRateAnnotationDemo")),
  "AnalyticsLoadingState": lazy(() => import("./preview-demos/AnalyticsLoadingStateDemo")),
  "AnalyticsMiniCard": lazy(() => import("./preview-demos/AnalyticsMiniCardDemo")),
  "AnalyticsMiniStatCard": lazy(() => import("./preview-demos/AnalyticsMiniStatCardDemo")),
  "ApprovalNoteDisplay": lazy(() => import("./preview-demos/ApprovalNoteDisplayDemo")),
  "ApproveRejectButtonPair": lazy(() => import("./preview-demos/ApproveRejectButtonPairDemo")),
  "AreaUnitConversionHint": lazy(() => import("./preview-demos/AreaUnitConversionHintDemo")),
  "AsymmetricTwoColLayout": lazy(() => import("./preview-demos/AsymmetricTwoColLayoutDemo")),
  "AttendancePctBadge": lazy(() => import("./preview-demos/AttendancePctBadgeDemo")),
  "AttendeeChipList": lazy(() => import("./preview-demos/AttendeeChipListDemo")),
  "AttendeeTogglePillSelector": lazy(() => import("./preview-demos/AttendeeTogglePillSelectorDemo")),
  "AuditLogEntryRow": lazy(() => import("./preview-demos/AuditLogEntryRowDemo")),
  "AuditLogRow": lazy(() => import("./preview-demos/AuditLogRowDemo")),
  "AutoCalculatedFieldHint": lazy(() => import("./preview-demos/AutoCalculatedFieldHintDemo")),
  "AutoEstimateHint": lazy(() => import("./preview-demos/AutoEstimateHintDemo")),
  "AutoFilledReadOnlyField": lazy(() => import("./preview-demos/AutoFilledReadOnlyFieldDemo")),
  "AvatarUploadField": lazy(() => import("./preview-demos/AvatarUploadFieldDemo")),
  "AvatarWithInitialsFallback": lazy(() => import("./preview-demos/AvatarWithInitialsFallbackDemo")),
  "AwaitingOwnerText": lazy(() => import("./preview-demos/AwaitingOwnerTextDemo")),
  "BackButton": lazy(() => import("./preview-demos/BackButtonDemo")),
  "BadgeWithIcon": lazy(() => import("./preview-demos/BadgeWithIconDemo")),
  "BalanceCheckCard": lazy(() => import("./preview-demos/BalanceCheckCardDemo")),
  "BalanceDueCard": lazy(() => import("./preview-demos/BalanceDueCardDemo")),
  "BalanceDuePanel": lazy(() => import("./preview-demos/BalanceDuePanelDemo")),
};

const BATCH_1 = {
  "BalanceStatusBadge": lazy(() => import("./preview-demos/BalanceStatusBadgeDemo")),
  "BankStatementEntryRow": lazy(() => import("./preview-demos/BankStatementEntryRowDemo")),
  "BeforeAfterGrid": lazy(() => import("./preview-demos/BeforeAfterGridDemo")),
  "BillUploadZone": lazy(() => import("./preview-demos/BillUploadZoneDemo")),
  "BinaryTypeBadge": lazy(() => import("./preview-demos/BinaryTypeBadgeDemo")),
  "BleedSectionDivider": lazy(() => import("./preview-demos/BleedSectionDividerDemo")),
  "BooleanActiveBadge": lazy(() => import("./preview-demos/BooleanActiveBadgeDemo")),
  "BooleanBadgeCell": lazy(() => import("./preview-demos/BooleanBadgeCellDemo")),
  "BoxOverlay": lazy(() => import("./preview-demos/BoxOverlayDemo")),
  "BreadcrumbHeader": lazy(() => import("./preview-demos/BreadcrumbHeaderDemo")),
  "BulkActionToolbar": lazy(() => import("./preview-demos/BulkActionToolbarDemo")),
  "BulkCheckboxPair": lazy(() => import("./preview-demos/BulkCheckboxPairDemo")),
  "BuyerContextCard": lazy(() => import("./preview-demos/BuyerContextCardDemo")),
  "CalendarDayEntryRow": lazy(() => import("./preview-demos/CalendarDayEntryRowDemo")),
  "CalendarDayPanel": lazy(() => import("./preview-demos/CalendarDayPanelDemo")),
  "CalendarEventItem": lazy(() => import("./preview-demos/CalendarEventItemDemo")),
  "CalendarLegendBar": lazy(() => import("./preview-demos/CalendarLegendBarDemo")),
  "CardEmptyState": lazy(() => import("./preview-demos/CardEmptyStateDemo")),
  "CardLoadingPlaceholder": lazy(() => import("./preview-demos/CardLoadingPlaceholderDemo")),
  "CategoryChip": lazy(() => import("./preview-demos/CategoryChipDemo")),
  "CategoryPill": lazy(() => import("./preview-demos/CategoryPillDemo")),
  "CenteredLoadingSpinner": lazy(() => import("./preview-demos/CenteredLoadingSpinnerDemo")),
  "ChannelTogglePicker": lazy(() => import("./preview-demos/ChannelTogglePickerDemo")),
  "CharacterCounter": lazy(() => import("./preview-demos/CharacterCounterDemo")),
  "ChartAreaEmptyState": lazy(() => import("./preview-demos/ChartAreaEmptyStateDemo")),
  "ChartCard": lazy(() => import("./preview-demos/ChartCardDemo")),
  "ChartCardWithHeader": lazy(() => import("./preview-demos/ChartCardWithHeaderDemo")),
  "ChartSectionCard": lazy(() => import("./preview-demos/ChartSectionCardDemo")),
  "CheckableLineItemRow": lazy(() => import("./preview-demos/CheckableLineItemRowDemo")),
  "CheckboxFieldGrid": lazy(() => import("./preview-demos/CheckboxFieldGridDemo")),
  "CheckboxFilterGroup": lazy(() => import("./preview-demos/CheckboxFilterGroupDemo")),
  "CheckboxPermissionGrid": lazy(() => import("./preview-demos/CheckboxPermissionGridDemo")),
  "ChecklistFileCell": lazy(() => import("./preview-demos/ChecklistFileCellDemo")),
  "ChecklistToggleCell": lazy(() => import("./preview-demos/ChecklistToggleCellDemo")),
  "ClaimLineEditor": lazy(() => import("./preview-demos/ClaimLineEditorDemo")),
  "ClaimStatusBadge": lazy(() => import("./preview-demos/ClaimStatusBadgeDemo")),
  "ClickableStatusPill": lazy(() => import("./preview-demos/ClickableStatusPillDemo")),
  "ClickableTableRow": lazy(() => import("./preview-demos/ClickableTableRowDemo")),
  "CollapsibleDetails": lazy(() => import("./preview-demos/CollapsibleDetailsDemo")),
  "CollapsibleFilterPanel": lazy(() => import("./preview-demos/CollapsibleFilterPanelDemo")),
  "CollapsibleFolderRow": lazy(() => import("./preview-demos/CollapsibleFolderRowDemo")),
  "CollapsibleSection": lazy(() => import("./preview-demos/CollapsibleSectionDemo")),
  "ColorCodedCurrencyCell": lazy(() => import("./preview-demos/ColorCodedCurrencyCellDemo")),
  "ColorCodedLedgerCells": lazy(() => import("./preview-demos/ColorCodedLedgerCellsDemo")),
  "ColorLegend": lazy(() => import("./preview-demos/ColorLegendDemo")),
  "ColoredDownloadCard": lazy(() => import("./preview-demos/ColoredDownloadCardDemo")),
  "ComboboxSearchSelect": lazy(() => import("./preview-demos/ComboboxSearchSelectDemo")),
  "CompactPaymentRow": lazy(() => import("./preview-demos/CompactPaymentRowDemo")),
  "CompanyCombobox": lazy(() => import("./preview-demos/CompanyComboboxDemo")),
  "CompanySearchCombobox": lazy(() => import("./preview-demos/CompanySearchComboboxDemo")),
};

const BATCH_2 = {
  "ComparisonColumnHeader": lazy(() => import("./preview-demos/ComparisonColumnHeaderDemo")),
  "ComputedAmountCell": lazy(() => import("./preview-demos/ComputedAmountCellDemo")),
  "ComputedReadonlySection": lazy(() => import("./preview-demos/ComputedReadonlySectionDemo")),
  "ComputedValidityDisplay": lazy(() => import("./preview-demos/ComputedValidityDisplayDemo")),
  "ConditionalColorBadge": lazy(() => import("./preview-demos/ConditionalColorBadgeDemo")),
  "ConditionalCountBadge": lazy(() => import("./preview-demos/ConditionalCountBadgeDemo")),
  "ConditionalStatsGrid": lazy(() => import("./preview-demos/ConditionalStatsGridDemo")),
  "ConditionallyClickableRow": lazy(() => import("./preview-demos/ConditionallyClickableRowDemo")),
  "ConditionallyDisabledActionButtons": lazy(() => import("./preview-demos/ConditionallyDisabledActionButtonsDemo")),
  "ConfidenceBadge": lazy(() => import("./preview-demos/ConfidenceBadgeDemo")),
  "ConfigWarningBanner": lazy(() => import("./preview-demos/ConfigWarningBannerDemo")),
  "ConfirmActionDialog": lazy(() => import("./preview-demos/ConfirmActionDialogDemo")),
  "ConfirmDeleteDialog": lazy(() => import("./preview-demos/ConfirmDeleteDialogDemo")),
  "CountTabBar": lazy(() => import("./preview-demos/CountTabBarDemo")),
  "CreatableCombobox": lazy(() => import("./preview-demos/CreatableComboboxDemo")),
  "CredentialsCopyRow": lazy(() => import("./preview-demos/CredentialsCopyRowDemo")),
  "CredentialsPanel": lazy(() => import("./preview-demos/CredentialsPanelDemo")),
  "CreditConditionalRow": lazy(() => import("./preview-demos/CreditConditionalRowDemo")),
  "CropSavedChip": lazy(() => import("./preview-demos/CropSavedChipDemo")),
  "CurrencyCell": lazy(() => import("./preview-demos/CurrencyCellDemo")),
  "CurrencyPreviewText": lazy(() => import("./preview-demos/CurrencyPreviewTextDemo")),
  "CustomerTypeChip": lazy(() => import("./preview-demos/CustomerTypeChipDemo")),
  "DashedGeneratePlaceholder": lazy(() => import("./preview-demos/DashedGeneratePlaceholderDemo")),
  "DataTable": lazy(() => import("./preview-demos/DataTableDemo")),
  "DateGroupLabel": lazy(() => import("./preview-demos/DateGroupLabelDemo")),
  "DateRangeFilterBarWithPresets": lazy(() => import("./preview-demos/DateRangeFilterBarWithPresetsDemo")),
  "DateRangeFilterPanel": lazy(() => import("./preview-demos/DateRangeFilterPanelDemo")),
  "DateRangeInline": lazy(() => import("./preview-demos/DateRangeInlineDemo")),
  "DateRangePicker": lazy(() => import("./preview-demos/DateRangePickerDemo")),
  "DateTimeCell": lazy(() => import("./preview-demos/DateTimeCellDemo")),
  "DebitAmountCell": lazy(() => import("./preview-demos/DebitAmountCellDemo")),
  "DeductionsSectionBlock": lazy(() => import("./preview-demos/DeductionsSectionBlockDemo")),
  "DerivedReadOnlyField": lazy(() => import("./preview-demos/DerivedReadOnlyFieldDemo")),
  "DestructiveOutlineButton": lazy(() => import("./preview-demos/DestructiveOutlineButtonDemo")),
  "DetailGrid": lazy(() => import("./preview-demos/DetailGridDemo")),
  "DetailLabelValueRow": lazy(() => import("./preview-demos/DetailLabelValueRowDemo")),
  "DetailLineItemsSubTable": lazy(() => import("./preview-demos/DetailLineItemsSubTableDemo")),
  "DetailSubTable": lazy(() => import("./preview-demos/DetailSubTableDemo")),
  "DetailSubTableInDialog": lazy(() => import("./preview-demos/DetailSubTableInDialogDemo")),
  "DialogContextLine": lazy(() => import("./preview-demos/DialogContextLineDemo")),
  "DialogFooterWithTotal": lazy(() => import("./preview-demos/DialogFooterWithTotalDemo")),
  "DialogFormFooter": lazy(() => import("./preview-demos/DialogFormFooterDemo")),
  "DialogKeyValueGrid": lazy(() => import("./preview-demos/DialogKeyValueGridDemo")),
  "DialogLabelValueRow": lazy(() => import("./preview-demos/DialogLabelValueRowDemo")),
  "DialogLoadingOverlay": lazy(() => import("./preview-demos/DialogLoadingOverlayDemo")),
  "DialogNetPaySummaryRow": lazy(() => import("./preview-demos/DialogNetPaySummaryRowDemo")),
  "DialogSectionSkeleton": lazy(() => import("./preview-demos/DialogSectionSkeletonDemo")),
  "DialogSectionSubheader": lazy(() => import("./preview-demos/DialogSectionSubheaderDemo")),
  "DialogUnderlineTabs": lazy(() => import("./preview-demos/DialogUnderlineTabsDemo")),
  "DisabledActionHint": lazy(() => import("./preview-demos/DisabledActionHintDemo")),
};

const BATCH_3 = {
  "DisabledFieldNotice": lazy(() => import("./preview-demos/DisabledFieldNoticeDemo")),
  "DocRow": lazy(() => import("./preview-demos/DocRowDemo")),
  "DocumentUploadCard": lazy(() => import("./preview-demos/DocumentUploadCardDemo")),
  "DoneStatusBadge": lazy(() => import("./preview-demos/DoneStatusBadgeDemo")),
  "DownloadReportCard": lazy(() => import("./preview-demos/DownloadReportCardDemo")),
  "DrillDownDetails": lazy(() => import("./preview-demos/DrillDownDetailsDemo")),
  "DueDateWithTime": lazy(() => import("./preview-demos/DueDateWithTimeDemo")),
  "DynamicFormRowList": lazy(() => import("./preview-demos/DynamicFormRowListDemo")),
  "EarningsLineItemRow": lazy(() => import("./preview-demos/EarningsLineItemRowDemo")),
  "EditableLineItemRow": lazy(() => import("./preview-demos/EditableLineItemRowDemo")),
  "EditableLineRow": lazy(() => import("./preview-demos/EditableLineRowDemo")),
  "EditableSubTableRow": lazy(() => import("./preview-demos/EditableSubTableRowDemo")),
  "EmployeeNameCell": lazy(() => import("./preview-demos/EmployeeNameCellDemo")),
  "EmployeeNameSubIdCell": lazy(() => import("./preview-demos/EmployeeNameSubIdCellDemo")),
  "EmployeeTableCell": lazy(() => import("./preview-demos/EmployeeTableCellDemo")),
  "EmptyRow": lazy(() => import("./preview-demos/EmptyRowDemo")),
  "EntityCodeSelectOption": lazy(() => import("./preview-demos/EntityCodeSelectOptionDemo")),
  "EntityToggleCard": lazy(() => import("./preview-demos/EntityToggleCardDemo")),
  "EntityTypeHeader": lazy(() => import("./preview-demos/EntityTypeHeaderDemo")),
  "ErrorAlertBanner": lazy(() => import("./preview-demos/ErrorAlertBannerDemo")),
  "ExpandableTableSubRow": lazy(() => import("./preview-demos/ExpandableTableSubRowDemo")),
  "ExportButtons": lazy(() => import("./preview-demos/ExportButtonsDemo")),
  "Field": lazy(() => import("./preview-demos/FieldDemo")),
  "FieldContextHint": lazy(() => import("./preview-demos/FieldContextHintDemo")),
  "FieldCountLabel": lazy(() => import("./preview-demos/FieldCountLabelDemo")),
  "FieldHintText": lazy(() => import("./preview-demos/FieldHintTextDemo")),
  "FieldToggleChip": lazy(() => import("./preview-demos/FieldToggleChipDemo")),
  "FieldWarningMessage": lazy(() => import("./preview-demos/FieldWarningMessageDemo")),
  "FileDropZone": lazy(() => import("./preview-demos/FileDropZoneDemo")),
  "FileListItemRow": lazy(() => import("./preview-demos/FileListItemRowDemo")),
  "FilePicker": lazy(() => import("./preview-demos/FilePickerDemo")),
  "FilePreviewTile": lazy(() => import("./preview-demos/FilePreviewTileDemo")),
  "FileUploadPreview": lazy(() => import("./preview-demos/FileUploadPreviewDemo")),
  "FileUploadStatusRow": lazy(() => import("./preview-demos/FileUploadStatusRowDemo")),
  "FilterControlCard": lazy(() => import("./preview-demos/FilterControlCardDemo")),
  "FilterCountBadge": lazy(() => import("./preview-demos/FilterCountBadgeDemo")),
  "FinancialFinalTotalRow": lazy(() => import("./preview-demos/FinancialFinalTotalRowDemo")),
  "FinancialRatioCard": lazy(() => import("./preview-demos/FinancialRatioCardDemo")),
  "FinancialTotalsRow": lazy(() => import("./preview-demos/FinancialTotalsRowDemo")),
  "FollowUpPromptDialog": lazy(() => import("./preview-demos/FollowUpPromptDialogDemo")),
  "FormField": lazy(() => import("./preview-demos/FormFieldDemo")),
  "FormFooter": lazy(() => import("./preview-demos/FormFooterDemo")),
  "FormSection": lazy(() => import("./preview-demos/FormSectionDemo")),
  "FormSectionLabel": lazy(() => import("./preview-demos/FormSectionLabelDemo")),
  "FractionCountBadge": lazy(() => import("./preview-demos/FractionCountBadgeDemo")),
  "FulfilmentBanner": lazy(() => import("./preview-demos/FulfilmentBannerDemo")),
  "FulfilmentStatusLine": lazy(() => import("./preview-demos/FulfilmentStatusLineDemo")),
  "FullPageLoadingText": lazy(() => import("./preview-demos/FullPageLoadingTextDemo")),
  "FullPageTextLoadingState": lazy(() => import("./preview-demos/FullPageTextLoadingStateDemo")),
  "GoogleMapsUrlInput": lazy(() => import("./preview-demos/GoogleMapsUrlInputDemo")),
};

const BATCH_4 = {
  "GpsPinButton": lazy(() => import("./preview-demos/GpsPinButtonDemo")),
  "GreetingHeader": lazy(() => import("./preview-demos/GreetingHeaderDemo")),
  "GroupedGallerySection": lazy(() => import("./preview-demos/GroupedGallerySectionDemo")),
  "GroupedPermissionCatalog": lazy(() => import("./preview-demos/GroupedPermissionCatalogDemo")),
  "GstMemoFootnote": lazy(() => import("./preview-demos/GstMemoFootnoteDemo")),
  "GstTaxBreakdownRows": lazy(() => import("./preview-demos/GstTaxBreakdownRowsDemo")),
  "GstTaxBreakdownSummary": lazy(() => import("./preview-demos/GstTaxBreakdownSummaryDemo")),
  "GstTotalsPanel": lazy(() => import("./preview-demos/GstTotalsPanelDemo")),
  "GstinInputWithFetch": lazy(() => import("./preview-demos/GstinInputWithFetchDemo")),
  "HealthListItem": lazy(() => import("./preview-demos/HealthListItemDemo")),
  "HealthScoreDisplay": lazy(() => import("./preview-demos/HealthScoreDisplayDemo")),
  "HiddenFileInputTrigger": lazy(() => import("./preview-demos/HiddenFileInputTriggerDemo")),
  "HorizontalBarRow": lazy(() => import("./preview-demos/HorizontalBarRowDemo")),
  "IconAvatar": lazy(() => import("./preview-demos/IconAvatarDemo")),
  "IconBadge": lazy(() => import("./preview-demos/IconBadgeDemo")),
  "IconCardHeader": lazy(() => import("./preview-demos/IconCardHeaderDemo")),
  "IconCircleEmptyState": lazy(() => import("./preview-demos/IconCircleEmptyStateDemo")),
  "IconContainer": lazy(() => import("./preview-demos/IconContainerDemo")),
  "IconLabelBodyRow": lazy(() => import("./preview-demos/IconLabelBodyRowDemo")),
  "IconMetricTile": lazy(() => import("./preview-demos/IconMetricTileDemo")),
  "IconNotificationRow": lazy(() => import("./preview-demos/IconNotificationRowDemo")),
  "IifeDialogBody": lazy(() => import("./preview-demos/IifeDialogBodyDemo")),
  "ImagePreviewWithRemove": lazy(() => import("./preview-demos/ImagePreviewWithRemoveDemo")),
  "ImportTileButton": lazy(() => import("./preview-demos/ImportTileButtonDemo")),
  "InactiveOpacityCard": lazy(() => import("./preview-demos/InactiveOpacityCardDemo")),
  "IncentiveCell": lazy(() => import("./preview-demos/IncentiveCellDemo")),
  "IncentiveSummaryFooter": lazy(() => import("./preview-demos/IncentiveSummaryFooterDemo")),
  "IndianCurrencyCell": lazy(() => import("./preview-demos/IndianCurrencyCellDemo")),
  "InfoBanner": lazy(() => import("./preview-demos/InfoBannerDemo")),
  "InlineAddRow": lazy(() => import("./preview-demos/InlineAddRowDemo")),
  "InlineAlert": lazy(() => import("./preview-demos/InlineAlertDemo")),
  "InlineCardEmptyState": lazy(() => import("./preview-demos/InlineCardEmptyStateDemo")),
  "InlineChartLegend": lazy(() => import("./preview-demos/InlineChartLegendDemo")),
  "InlineChevronLink": lazy(() => import("./preview-demos/InlineChevronLinkDemo")),
  "InlineDateRangeFilter": lazy(() => import("./preview-demos/InlineDateRangeFilterDemo")),
  "InlineDecimalInput": lazy(() => import("./preview-demos/InlineDecimalInputDemo")),
  "InlineDialogLoadingState": lazy(() => import("./preview-demos/InlineDialogLoadingStateDemo")),
  "InlineDocumentIndicator": lazy(() => import("./preview-demos/InlineDocumentIndicatorDemo")),
  "InlineDownloadButton": lazy(() => import("./preview-demos/InlineDownloadButtonDemo")),
  "InlineEditableTableCell": lazy(() => import("./preview-demos/InlineEditableTableCellDemo")),
  "InlineInputValidationError": lazy(() => import("./preview-demos/InlineInputValidationErrorDemo")),
  "InlineLabelValueGrid": lazy(() => import("./preview-demos/InlineLabelValueGridDemo")),
  "InlineLoadingSwap": lazy(() => import("./preview-demos/InlineLoadingSwapDemo")),
  "InlineMonthFilter": lazy(() => import("./preview-demos/InlineMonthFilterDemo")),
  "InlinePill": lazy(() => import("./preview-demos/InlinePillDemo")),
  "InlinePillStatus": lazy(() => import("./preview-demos/InlinePillStatusDemo")),
  "InlineRejectionReason": lazy(() => import("./preview-demos/InlineRejectionReasonDemo")),
  "InlineRowConfirm": lazy(() => import("./preview-demos/InlineRowConfirmDemo")),
  "InlineSaveOnChange": lazy(() => import("./preview-demos/InlineSaveOnChangeDemo")),
  "InlineSpinnerButton": lazy(() => import("./preview-demos/InlineSpinnerButtonDemo")),
};

const BATCH_5 = {
  "InlineSpinnerButtonSwap": lazy(() => import("./preview-demos/InlineSpinnerButtonSwapDemo")),
  "InlineStatusPill": lazy(() => import("./preview-demos/InlineStatusPillDemo")),
  "InlineStatusText": lazy(() => import("./preview-demos/InlineStatusTextDemo")),
  "InlineTextContentSection": lazy(() => import("./preview-demos/InlineTextContentSectionDemo")),
  "InlineWarningBanner": lazy(() => import("./preview-demos/InlineWarningBannerDemo")),
  "InsightSection": lazy(() => import("./preview-demos/InsightSectionDemo")),
  "InteractiveImageCropCanvas": lazy(() => import("./preview-demos/InteractiveImageCropCanvasDemo")),
  "InventoryMetricTile": lazy(() => import("./preview-demos/InventoryMetricTileDemo")),
  "InventoryProductCard": lazy(() => import("./preview-demos/InventoryProductCardDemo")),
  "InventoryStatGrid": lazy(() => import("./preview-demos/InventoryStatGridDemo")),
  "InvoiceLineItemRow": lazy(() => import("./preview-demos/InvoiceLineItemRowDemo")),
  "InvoiceMatchPickerRow": lazy(() => import("./preview-demos/InvoiceMatchPickerRowDemo")),
  "InvoiceTotalsPreview": lazy(() => import("./preview-demos/InvoiceTotalsPreviewDemo")),
  "IssueCreditNoteDialog": lazy(() => import("./preview-demos/IssueCreditNoteDialogDemo")),
  "JournalMetaRow": lazy(() => import("./preview-demos/JournalMetaRowDemo")),
  "KanbanColumn": lazy(() => import("./preview-demos/KanbanColumnDemo")),
  "KanbanColumnHeader": lazy(() => import("./preview-demos/KanbanColumnHeaderDemo")),
  "KanbanDealCard": lazy(() => import("./preview-demos/KanbanDealCardDemo")),
  "KanbanTaskCard": lazy(() => import("./preview-demos/KanbanTaskCardDemo")),
  "KeyValuePanel": lazy(() => import("./preview-demos/KeyValuePanelDemo")),
  "KeyValueRow": lazy(() => import("./preview-demos/KeyValueRowDemo")),
  "LabelValueField": lazy(() => import("./preview-demos/LabelValueFieldDemo")),
  "LabelWithHint": lazy(() => import("./preview-demos/LabelWithHintDemo")),
  "LabelWrappedField": lazy(() => import("./preview-demos/LabelWrappedFieldDemo")),
  "LabeledField": lazy(() => import("./preview-demos/LabeledFieldDemo")),
  "LabeledHeaderControl": lazy(() => import("./preview-demos/LabeledHeaderControlDemo")),
  "LazyHydrateDialog": lazy(() => import("./preview-demos/LazyHydrateDialogDemo")),
  "LeafletMapModal": lazy(() => import("./preview-demos/LeafletMapModalDemo")),
  "LeaveBalanceColumns": lazy(() => import("./preview-demos/LeaveBalanceColumnsDemo")),
  "LeaveTypeCard": lazy(() => import("./preview-demos/LeaveTypeCardDemo")),
  "LifecycleActionDialog": lazy(() => import("./preview-demos/LifecycleActionDialogDemo")),
  "LightboxOverlay": lazy(() => import("./preview-demos/LightboxOverlayDemo")),
  "LineItemCard": lazy(() => import("./preview-demos/LineItemCardDemo")),
  "LineItemRow": lazy(() => import("./preview-demos/LineItemRowDemo")),
  "LineItemSubRow": lazy(() => import("./preview-demos/LineItemSubRowDemo")),
  "LineItemWithSubnote": lazy(() => import("./preview-demos/LineItemWithSubnoteDemo")),
  "LineItemsEditorSection": lazy(() => import("./preview-demos/LineItemsEditorSectionDemo")),
  "LineTotalsFooterRow": lazy(() => import("./preview-demos/LineTotalsFooterRowDemo")),
  "LinkedEntityCell": lazy(() => import("./preview-demos/LinkedEntityCellDemo")),
  "LiveTotalsPreview": lazy(() => import("./preview-demos/LiveTotalsPreviewDemo")),
  "LoadMoreButton": lazy(() => import("./preview-demos/LoadMoreButtonDemo")),
  "LoadingButtonIconSwap": lazy(() => import("./preview-demos/LoadingButtonIconSwapDemo")),
  "LoadingSpinnerButton": lazy(() => import("./preview-demos/LoadingSpinnerButtonDemo")),
  "LoadingTextSwap": lazy(() => import("./preview-demos/LoadingTextSwapDemo")),
  "LocPin": lazy(() => import("./preview-demos/LocPinDemo")),
  "LowStockAlertRow": lazy(() => import("./preview-demos/LowStockAlertRowDemo")),
  "MapLinkButton": lazy(() => import("./preview-demos/MapLinkButtonDemo")),
  "MapStatusLegend": lazy(() => import("./preview-demos/MapStatusLegendDemo")),
  "MarketplaceLegendRow": lazy(() => import("./preview-demos/MarketplaceLegendRowDemo")),
  "MatchConfidenceChip": lazy(() => import("./preview-demos/MatchConfidenceChipDemo")),
};

const BATCH_6 = {
  "MediaCard": lazy(() => import("./preview-demos/MediaCardDemo")),
  "MediaLightbox": lazy(() => import("./preview-demos/MediaLightboxDemo")),
  "MediaLinkRow": lazy(() => import("./preview-demos/MediaLinkRowDemo")),
  "MediaThumbnailCard": lazy(() => import("./preview-demos/MediaThumbnailCardDemo")),
  "MeetingMediaPanel": lazy(() => import("./preview-demos/MeetingMediaPanelDemo")),
  "MiniStat": lazy(() => import("./preview-demos/MiniStatDemo")),
  "MiniStatChip": lazy(() => import("./preview-demos/MiniStatChipDemo")),
  "MiniStatTile": lazy(() => import("./preview-demos/MiniStatTileDemo")),
  "MonoCodeCell": lazy(() => import("./preview-demos/MonoCodeCellDemo")),
  "MonoCodeText": lazy(() => import("./preview-demos/MonoCodeTextDemo")),
  "MonospaceSecretBlock": lazy(() => import("./preview-demos/MonospaceSecretBlockDemo")),
  "MonospaceTokenDisplay": lazy(() => import("./preview-demos/MonospaceTokenDisplayDemo")),
  "MonthYearPeriodFilter": lazy(() => import("./preview-demos/MonthYearPeriodFilterDemo")),
  "MonthYearSelectPair": lazy(() => import("./preview-demos/MonthYearSelectPairDemo")),
  "MultiFieldFilterBar": lazy(() => import("./preview-demos/MultiFieldFilterBarDemo")),
  "MultiStateSettingsPanel": lazy(() => import("./preview-demos/MultiStateSettingsPanelDemo")),
  "MultiStatusBadgeCell": lazy(() => import("./preview-demos/MultiStatusBadgeCellDemo")),
  "MutedLabelChip": lazy(() => import("./preview-demos/MutedLabelChipDemo")),
  "NameWithIdSubtext": lazy(() => import("./preview-demos/NameWithIdSubtextDemo")),
  "NameWithSublineCell": lazy(() => import("./preview-demos/NameWithSublineCellDemo")),
  "NativeFyYearSelect": lazy(() => import("./preview-demos/NativeFyYearSelectDemo")),
  "NativeSelectField": lazy(() => import("./preview-demos/NativeSelectFieldDemo")),
  "NativeSelectInput": lazy(() => import("./preview-demos/NativeSelectInputDemo")),
  "NegativeAmountDisplay": lazy(() => import("./preview-demos/NegativeAmountDisplayDemo")),
  "NestedTableInCard": lazy(() => import("./preview-demos/NestedTableInCardDemo")),
  "NestedZoneTable": lazy(() => import("./preview-demos/NestedZoneTableDemo")),
  "NetPayHighlightCell": lazy(() => import("./preview-demos/NetPayHighlightCellDemo")),
  "NetPaySummaryRow": lazy(() => import("./preview-demos/NetPaySummaryRowDemo")),
  "NetProfitBanner": lazy(() => import("./preview-demos/NetProfitBannerDemo")),
  "NotReadyBanner": lazy(() => import("./preview-demos/NotReadyBannerDemo")),
  "NotificationItemRow": lazy(() => import("./preview-demos/NotificationItemRowDemo")),
  "NotificationSkeletonRow": lazy(() => import("./preview-demos/NotificationSkeletonRowDemo")),
  "NullableEntitySelect": lazy(() => import("./preview-demos/NullableEntitySelectDemo")),
  "NumberedStepList": lazy(() => import("./preview-demos/NumberedStepListDemo")),
  "OptionButtonGroup": lazy(() => import("./preview-demos/OptionButtonGroupDemo")),
  "OtherChargeLineItem": lazy(() => import("./preview-demos/OtherChargeLineItemDemo")),
  "OtherOptionReveal": lazy(() => import("./preview-demos/OtherOptionRevealDemo")),
  "OutlookBanner": lazy(() => import("./preview-demos/OutlookBannerDemo")),
  "OutstandingTable": lazy(() => import("./preview-demos/OutstandingTableDemo")),
  "OverdueDateCell": lazy(() => import("./preview-demos/OverdueDateCellDemo")),
  "PLRow": lazy(() => import("./preview-demos/PLRowDemo")),
  "PLSummaryRow": lazy(() => import("./preview-demos/PLSummaryRowDemo")),
  "PageHeader": lazy(() => import("./preview-demos/PageHeaderDemo")),
  "PageHeaderWithSubtitle": lazy(() => import("./preview-demos/PageHeaderWithSubtitleDemo")),
  "PageTitleWithSubtitle": lazy(() => import("./preview-demos/PageTitleWithSubtitleDemo")),
  "PaginationControls": lazy(() => import("./preview-demos/PaginationControlsDemo")),
  "PaidUnpaidBadge": lazy(() => import("./preview-demos/PaidUnpaidBadgeDemo")),
  "PanelCard": lazy(() => import("./preview-demos/PanelCardDemo")),
  "PasswordInputWithGenerate": lazy(() => import("./preview-demos/PasswordInputWithGenerateDemo")),
  "PaymentHistoryEntry": lazy(() => import("./preview-demos/PaymentHistoryEntryDemo")),
};

const BATCH_7 = {
  "PaymentReminderDialog": lazy(() => import("./preview-demos/PaymentReminderDialogDemo")),
  "PaymentSideLabel": lazy(() => import("./preview-demos/PaymentSideLabelDemo")),
  "PayslipFinancialSection": lazy(() => import("./preview-demos/PayslipFinancialSectionDemo")),
  "PayslipViewDialog": lazy(() => import("./preview-demos/PayslipViewDialogDemo")),
  "PercentageInputWithSuffix": lazy(() => import("./preview-demos/PercentageInputWithSuffixDemo")),
  "PercentageSumIndicator": lazy(() => import("./preview-demos/PercentageSumIndicatorDemo")),
  "PeriodSelectorPanel": lazy(() => import("./preview-demos/PeriodSelectorPanelDemo")),
  "PermissionCycleBadge": lazy(() => import("./preview-demos/PermissionCycleBadgeDemo")),
  "PhotoLightbox": lazy(() => import("./preview-demos/PhotoLightboxDemo")),
  "PhotoThumbnail": lazy(() => import("./preview-demos/PhotoThumbnailDemo")),
  "PillTabs": lazy(() => import("./preview-demos/PillTabsDemo")),
  "PipelineStageButton": lazy(() => import("./preview-demos/PipelineStageButtonDemo")),
  "PlanSummaryCard": lazy(() => import("./preview-demos/PlanSummaryCardDemo")),
  "PlatformMetricCard": lazy(() => import("./preview-demos/PlatformMetricCardDemo")),
  "PlatformSummaryCard": lazy(() => import("./preview-demos/PlatformSummaryCardDemo")),
  "PnlRow": lazy(() => import("./preview-demos/PnlRowDemo")),
  "PolicyWarningInline": lazy(() => import("./preview-demos/PolicyWarningInlineDemo")),
  "PostActionChainDialog": lazy(() => import("./preview-demos/PostActionChainDialogDemo")),
  "PriceBreakdownPanel": lazy(() => import("./preview-demos/PriceBreakdownPanelDemo")),
  "PricePerUnitBanner": lazy(() => import("./preview-demos/PricePerUnitBannerDemo")),
  "PricingBreakdownCard": lazy(() => import("./preview-demos/PricingBreakdownCardDemo")),
  "PricingPlanCard": lazy(() => import("./preview-demos/PricingPlanCardDemo")),
  "PrimarySubValueCell": lazy(() => import("./preview-demos/PrimarySubValueCellDemo")),
  "PrintDocumentFooter": lazy(() => import("./preview-demos/PrintDocumentFooterDemo")),
  "PriorityBadge": lazy(() => import("./preview-demos/PriorityBadgeDemo")),
  "ProductCombobox": lazy(() => import("./preview-demos/ProductComboboxDemo")),
  "ProductComboboxCell": lazy(() => import("./preview-demos/ProductComboboxCellDemo")),
  "ProductSearchDropdown": lazy(() => import("./preview-demos/ProductSearchDropdownDemo")),
  "PropertyCompactCard": lazy(() => import("./preview-demos/PropertyCompactCardDemo")),
  "PropertyMapCard": lazy(() => import("./preview-demos/PropertyMapCardDemo")),
  "PropertyMatchCTA": lazy(() => import("./preview-demos/PropertyMatchCTADemo")),
  "PurchasedPropertyRow": lazy(() => import("./preview-demos/PurchasedPropertyRowDemo")),
  "QrCodeViewDialog": lazy(() => import("./preview-demos/QrCodeViewDialogDemo")),
  "RaciLegend": lazy(() => import("./preview-demos/RaciLegendDemo")),
  "RaciMatrixTable": lazy(() => import("./preview-demos/RaciMatrixTableDemo")),
  "RaciRolePill": lazy(() => import("./preview-demos/RaciRolePillDemo")),
  "ReadOnlyComputedInput": lazy(() => import("./preview-demos/ReadOnlyComputedInputDemo")),
  "ReceiptMetaSpread": lazy(() => import("./preview-demos/ReceiptMetaSpreadDemo")),
  "ReceiptPrintHeader": lazy(() => import("./preview-demos/ReceiptPrintHeaderDemo")),
  "RecentUploadRow": lazy(() => import("./preview-demos/RecentUploadRowDemo")),
  "RecordPaymentDialog": lazy(() => import("./preview-demos/RecordPaymentDialogDemo")),
  "RecurringTemplateToggleRow": lazy(() => import("./preview-demos/RecurringTemplateToggleRowDemo")),
  "RefreshSpinButton": lazy(() => import("./preview-demos/RefreshSpinButtonDemo")),
  "RegisterEmployeeBlock": lazy(() => import("./preview-demos/RegisterEmployeeBlockDemo")),
  "RejectionReasonHint": lazy(() => import("./preview-demos/RejectionReasonHintDemo")),
  "RenderFormBody": lazy(() => import("./preview-demos/RenderFormBodyDemo")),
  "ReportCard": lazy(() => import("./preview-demos/ReportCardDemo")),
  "ReportFilterBar": lazy(() => import("./preview-demos/ReportFilterBarDemo")),
  "ReportRows": lazy(() => import("./preview-demos/ReportRowsDemo")),
  "RequiredFieldLabel": lazy(() => import("./preview-demos/RequiredFieldLabelDemo")),
};

const BATCH_8 = {
  "ResetSortButton": lazy(() => import("./preview-demos/ResetSortButtonDemo")),
  "ResultDownloadPanel": lazy(() => import("./preview-demos/ResultDownloadPanelDemo")),
  "RoleBadge": lazy(() => import("./preview-demos/RoleBadgeDemo")),
  "RoleCard": lazy(() => import("./preview-demos/RoleCardDemo")),
  "SaveButtonWithSpinner": lazy(() => import("./preview-demos/SaveButtonWithSpinnerDemo")),
  "ScanSuccessOverlay": lazy(() => import("./preview-demos/ScanSuccessOverlayDemo")),
  "ScheduledChangeBanner": lazy(() => import("./preview-demos/ScheduledChangeBannerDemo")),
  "ScrollableListSection": lazy(() => import("./preview-demos/ScrollableListSectionDemo")),
  "SearchCombo": lazy(() => import("./preview-demos/SearchComboDemo")),
  "SearchInput": lazy(() => import("./preview-demos/SearchInputDemo")),
  "SearchableCombobox": lazy(() => import("./preview-demos/SearchableComboboxDemo")),
  "SearchableEntityPicker": lazy(() => import("./preview-demos/SearchableEntityPickerDemo")),
  "SecondaryPill": lazy(() => import("./preview-demos/SecondaryPillDemo")),
  "SectionCard": lazy(() => import("./preview-demos/SectionCardDemo")),
  "SectionCountSuffix": lazy(() => import("./preview-demos/SectionCountSuffixDemo")),
  "SectionPermissionBlock": lazy(() => import("./preview-demos/SectionPermissionBlockDemo")),
  "SectionSkeletonGrid": lazy(() => import("./preview-demos/SectionSkeletonGridDemo")),
  "SectionSkeletonList": lazy(() => import("./preview-demos/SectionSkeletonListDemo")),
  "SectionSkeletonLoader": lazy(() => import("./preview-demos/SectionSkeletonLoaderDemo")),
  "SectionSkeletonPlaceholder": lazy(() => import("./preview-demos/SectionSkeletonPlaceholderDemo")),
  "SectionSkeletonStack": lazy(() => import("./preview-demos/SectionSkeletonStackDemo")),
  "SegmentedControl": lazy(() => import("./preview-demos/SegmentedControlDemo")),
  "SegmentedTabBar": lazy(() => import("./preview-demos/SegmentedTabBarDemo")),
  "SegmentedToggle": lazy(() => import("./preview-demos/SegmentedToggleDemo")),
  "SelectAllResetBar": lazy(() => import("./preview-demos/SelectAllResetBarDemo")),
  "SelectWithHint": lazy(() => import("./preview-demos/SelectWithHintDemo")),
  "SelectedItemChip": lazy(() => import("./preview-demos/SelectedItemChipDemo")),
  "SelectionCountDropdownItem": lazy(() => import("./preview-demos/SelectionCountDropdownItemDemo")),
  "SeverityChip": lazy(() => import("./preview-demos/SeverityChipDemo")),
  "ShiftCell": lazy(() => import("./preview-demos/ShiftCellDemo")),
  "SideLockedBadge": lazy(() => import("./preview-demos/SideLockedBadgeDemo")),
  "SignedCurrencyCell": lazy(() => import("./preview-demos/SignedCurrencyCellDemo")),
  "SignedCurrencyValue": lazy(() => import("./preview-demos/SignedCurrencyValueDemo")),
  "SimulationResultPanel": lazy(() => import("./preview-demos/SimulationResultPanelDemo")),
  "SortIcon": lazy(() => import("./preview-demos/SortIconDemo")),
  "SortableHeader": lazy(() => import("./preview-demos/SortableHeaderDemo")),
  "SourceBadge": lazy(() => import("./preview-demos/SourceBadgeDemo")),
  "SpinnerSwapButton": lazy(() => import("./preview-demos/SpinnerSwapButtonDemo")),
  "StageEditorRow": lazy(() => import("./preview-demos/StageEditorRowDemo")),
  "StatCardSkeleton": lazy(() => import("./preview-demos/StatCardSkeletonDemo")),
  "StateTransitionDisplay": lazy(() => import("./preview-demos/StateTransitionDisplayDemo")),
  "StatsGridSkeleton": lazy(() => import("./preview-demos/StatsGridSkeletonDemo")),
  "StatusBadge": lazy(() => import("./preview-demos/StatusBadgeDemo")),
  "StatusDot": lazy(() => import("./preview-demos/StatusDotDemo")),
  "StatusPill": lazy(() => import("./preview-demos/StatusPillDemo")),
  "StatusTransitionArrow": lazy(() => import("./preview-demos/StatusTransitionArrowDemo")),
  "Stepper": lazy(() => import("./preview-demos/StepperDemo")),
  "SubjectNoteCell": lazy(() => import("./preview-demos/SubjectNoteCellDemo")),
  "SubscriptionStatusPill": lazy(() => import("./preview-demos/SubscriptionStatusPillDemo")),
  "SuccessConfirmationDialog": lazy(() => import("./preview-demos/SuccessConfirmationDialogDemo")),
};

const BATCH_9 = {
  "SuccessIconCircle": lazy(() => import("./preview-demos/SuccessIconCircleDemo")),
  "SuccessNotificationBox": lazy(() => import("./preview-demos/SuccessNotificationBoxDemo")),
  "SuggestedValueHint": lazy(() => import("./preview-demos/SuggestedValueHintDemo")),
  "SummaryKeyValueList": lazy(() => import("./preview-demos/SummaryKeyValueListDemo")),
  "SummaryKeyValueRow": lazy(() => import("./preview-demos/SummaryKeyValueRowDemo")),
  "SummaryMetricTile": lazy(() => import("./preview-demos/SummaryMetricTileDemo")),
  "SupplyTypeToggleButton": lazy(() => import("./preview-demos/SupplyTypeToggleButtonDemo")),
  "SwitchLabelRow": lazy(() => import("./preview-demos/SwitchLabelRowDemo")),
  "SwitchRow": lazy(() => import("./preview-demos/SwitchRowDemo")),
  "SwitchToggleRow": lazy(() => import("./preview-demos/SwitchToggleRowDemo")),
  "SwitchWithLabel": lazy(() => import("./preview-demos/SwitchWithLabelDemo")),
  "SystemResourceBadge": lazy(() => import("./preview-demos/SystemResourceBadgeDemo")),
  "TabPlaceholderCard": lazy(() => import("./preview-demos/TabPlaceholderCardDemo")),
  "TabSwitcherBar": lazy(() => import("./preview-demos/TabSwitcherBarDemo")),
  "TabbedDetailDialog": lazy(() => import("./preview-demos/TabbedDetailDialogDemo")),
  "TableCard": lazy(() => import("./preview-demos/TableCardDemo")),
  "TableSkeleton": lazy(() => import("./preview-demos/TableSkeletonDemo")),
  "TableTotalsRow": lazy(() => import("./preview-demos/TableTotalsRowDemo")),
  "TagChipRow": lazy(() => import("./preview-demos/TagChipRowDemo")),
  "TemperatureBadge": lazy(() => import("./preview-demos/TemperatureBadgeDemo")),
  "TextareaCharCounter": lazy(() => import("./preview-demos/TextareaCharCounterDemo")),
  "ThreeStateToggleButton": lazy(() => import("./preview-demos/ThreeStateToggleButtonDemo")),
  "TimelineEntry": lazy(() => import("./preview-demos/TimelineEntryDemo")),
  "TimelineEventIcon": lazy(() => import("./preview-demos/TimelineEventIconDemo")),
  "TimestampCell": lazy(() => import("./preview-demos/TimestampCellDemo")),
  "TitleWithSubtextCell": lazy(() => import("./preview-demos/TitleWithSubtextCellDemo")),
  "TogglableStatusBadge": lazy(() => import("./preview-demos/TogglableStatusBadgeDemo")),
  "ToggleStatusBadge": lazy(() => import("./preview-demos/ToggleStatusBadgeDemo")),
  "ToggleTextButton": lazy(() => import("./preview-demos/ToggleTextButtonDemo")),
  "TonedAlertBox": lazy(() => import("./preview-demos/TonedAlertBoxDemo")),
  "TotalsGrandRow": lazy(() => import("./preview-demos/TotalsGrandRowDemo")),
  "TotalsRow": lazy(() => import("./preview-demos/TotalsRowDemo")),
  "TotalsTableRow": lazy(() => import("./preview-demos/TotalsTableRowDemo")),
  "TranscribeButton": lazy(() => import("./preview-demos/TranscribeButtonDemo")),
  "TruncatedCellWithNativeTooltip": lazy(() => import("./preview-demos/TruncatedCellWithNativeTooltipDemo")),
  "TruncatedListWithOverflow": lazy(() => import("./preview-demos/TruncatedListWithOverflowDemo")),
  "TruncatedMonoCell": lazy(() => import("./preview-demos/TruncatedMonoCellDemo")),
  "TruncatedTextCell": lazy(() => import("./preview-demos/TruncatedTextCellDemo")),
  "TwoColumnAccountingLayout": lazy(() => import("./preview-demos/TwoColumnAccountingLayoutDemo")),
  "TwoColumnEntityBlock": lazy(() => import("./preview-demos/TwoColumnEntityBlockDemo")),
  "TwoColumnInfoCard": lazy(() => import("./preview-demos/TwoColumnInfoCardDemo")),
  "TwoLineCell": lazy(() => import("./preview-demos/TwoLineCellDemo")),
  "TwoLineCellWithMono": lazy(() => import("./preview-demos/TwoLineCellWithMonoDemo")),
  "TwoLineTableCell": lazy(() => import("./preview-demos/TwoLineTableCellDemo")),
  "TypeBadge": lazy(() => import("./preview-demos/TypeBadgeDemo")),
  "TypeaheadDropdown": lazy(() => import("./preview-demos/TypeaheadDropdownDemo")),
  "UnderlineTabBar": lazy(() => import("./preview-demos/UnderlineTabBarDemo")),
  "UnderlineTabs": lazy(() => import("./preview-demos/UnderlineTabsDemo")),
  "UnitSelect": lazy(() => import("./preview-demos/UnitSelectDemo")),
  "UnreadCountBadge": lazy(() => import("./preview-demos/UnreadCountBadgeDemo")),
};

const BATCH_10 = {
  "UpDownReorderControls": lazy(() => import("./preview-demos/UpDownReorderControlsDemo")),
  "UserListItem": lazy(() => import("./preview-demos/UserListItemDemo")),
  "UserProfileCell": lazy(() => import("./preview-demos/UserProfileCellDemo")),
  "ValueWithSubLabel": lazy(() => import("./preview-demos/ValueWithSubLabelDemo")),
  "VarianceBadge": lazy(() => import("./preview-demos/VarianceBadgeDemo")),
  "VendorAutocompleteDropdown": lazy(() => import("./preview-demos/VendorAutocompleteDropdownDemo")),
  "VideoPlayButtonOverlay": lazy(() => import("./preview-demos/VideoPlayButtonOverlayDemo")),
  "ViewAllLink": lazy(() => import("./preview-demos/ViewAllLinkDemo")),
  "ViewModeToggle": lazy(() => import("./preview-demos/ViewModeToggleDemo")),
  "ViewToggleTabs": lazy(() => import("./preview-demos/ViewToggleTabsDemo")),
  "VoiceNoteRecorder": lazy(() => import("./preview-demos/VoiceNoteRecorderDemo")),
  "WarningTableCard": lazy(() => import("./preview-demos/WarningTableCardDemo")),
  "YearRangeSelect": lazy(() => import("./preview-demos/YearRangeSelectDemo")),
};

const ALL_DEMOS: Record<string, React.LazyExoticComponent<() => JSX.Element | null>> = {
  ...BATCH_0,
  ...BATCH_1,
  ...BATCH_2,
  ...BATCH_3,
  ...BATCH_4,
  ...BATCH_5,
  ...BATCH_6,
  ...BATCH_7,
  ...BATCH_8,
  ...BATCH_9,
  ...BATCH_10,
};

// Per-demo error boundary so one broken demo doesn't crash the whole page
class DemoErrorBoundary extends Component<{children: React.ReactNode}, {error: boolean}> {
  state = { error: false };
  static getDerivedStateFromError() { return { error: true }; }
  render() {
    if (this.state.error) return <div className="p-4 text-sm text-muted-foreground">Preview unavailable</div>;
    return this.props.children;
  }
}

export default function ComponentPreview() {
  const [params] = useSearchParams();
  const name = params.get("name") ?? "";
  const Demo = ALL_DEMOS[name];

  useEffect(() => { document.title = name || "Preview"; }, [name]);

  if (!name) return <div className="p-8 text-muted-foreground text-sm">Use ?name=ComponentName</div>;
  if (!Demo) return <div className="p-8 text-muted-foreground text-sm">No preview for: {name}</div>;

  return (
    <div className="p-8 bg-white min-h-screen">
      <DemoErrorBoundary>
        <Suspense fallback={<div className="p-4 text-sm text-muted-foreground">Loading...</div>}>
          <Demo />
        </Suspense>
      </DemoErrorBoundary>
    </div>
  );
}
